[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[lib]
name = "agent"
path= "src/lib.rs"

[dependencies]
libm = "0.2.11"
ordered-float = "5.0.0"
petgraph = "0.7.1"
rand = "0.9.0"
rand_distr = "0.5.1"
